.TH VIEWBRIF 1 "Sep 28 2015" LOCAL "General Commands Manual"
.SH NAME 
viewbrif - GUI BRIf File Viewer. 

.SH SYNOPSIS 
.B viewbrif [file]

.SH DESCRIPTION 
Visualizes BRIF files.

.SH SOURCE
Source available at https://github.com/ac000/viewbrif under the GNU GPLv2

.SH AUTHORS
Andrew Clayton <andrew@digital-domain.net> - Main author

Graham Thomson <g.thomson@pccl.co.uk> - Stats fix's
